# Generated by Django 5.2 on 2025-07-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockSplit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=10)),
                ("date", models.DateField()),
                (
                    "split",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Split ratio (e.g., 2.0 for a 2:1 split, 0.5 for a 1:2 reverse split)",
                        max_digits=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-date", "symbol"],
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("symbol", models.CharField(max_length=10)),
                ("quantity", models.IntegerField()),
                ("adjusted_quantity", models.IntegerField(blank=True, null=True)),
                (
                    "price_per_share",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "adjusted_price_per_share",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("CAD", "CAD")],
                        default="USD",
                        max_length=3,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "symbol"],
            },
        ),
    ]
