# Generated by Django 5.2 on 2025-07-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction_adjuster", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransaction",
            name="type",
            field=models.CharField(
                choices=[("buy", "Buy"), ("sell", "Sell")], default="buy", max_length=4
            ),
        ),
    ]
