# Generated by Django 4.2.2 on 2023-06-27 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "currency",
                    models.CharField(choices=[(1, "USD"), (2, "CAD")], max_length=255),
                ),
                ("market", models.CharField(max_length=10)),
                ("google_ticker", models.CharField(max_length=10)),
                ("yahoo_ticker", models.CharField(max_length=10)),
                ("seekingalpha_ticker", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("low", models.FloatField()),
                ("high", models.FloatField()),
                ("average", models.FloatField()),
                ("open", models.FloatField()),
                ("close", models.FloatField()),
                ("volume", models.IntegerField()),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="watcher.stock"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Cheapest In X Days"),
                            (2, "Most Expensive In X Days"),
                            (3, "Lower Than"),
                            (4, "Higher Than"),
                        ]
                    ),
                ),
                ("days", models.PositiveSmallIntegerField()),
                ("value", models.FloatField(max_length=255)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="watcher.stock"
                    ),
                ),
            ],
        ),
    ]
