# Generated by Django 4.2.2 on 2023-06-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watcher", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="currency",
            field=models.CharField(
                choices=[("USD", "USD"), ("CAD", "CAD")], max_length=255
            ),
        ),
        migrations.AddConstraint(
            model_name="price",
            constraint=models.UniqueConstraint(
                fields=("stock", "date"), name="unique_stock_date"
            ),
        ),
    ]
