# Generated by Django 4.2.2 on 2023-07-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watcher", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alert",
            options={"ordering": ["stock", "type"]},
        ),
        migrations.AlterModelOptions(
            name="price",
            options={"ordering": ["-date", "stock"]},
        ),
        migrations.AlterModelOptions(
            name="stock",
            options={"ordering": ["name"]},
        ),
    ]
