# Generated by Django 4.2.2 on 2023-06-29 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watcher", "0002_alter_stock_currency_price_unique_stock_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="average",
        ),
    ]
