# Generated by Django 4.2.2 on 2023-07-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watcher", "0002_alter_alert_options_alter_price_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="currency",
            field=models.CharField(
                choices=[("USD", "USD"), ("CAD", "CAD")], default="USD", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="market",
            field=models.CharField(default="NASDAQ", max_length=10),
        ),
    ]
