# Generated by Django 4.2.2 on 2023-07-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watcher", "0003_remove_price_average"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="date_last_fetch",
            field=models.DateField(blank=True, null=True),
        ),
    ]
