# Generated by Django 5.1.4 on 2025-01-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watcher", "0004_remove_stock_alphavantage_symbol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="dividend_yield",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=4
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Minimum number of days for interval alerts",
            ),
        ),
        migrations.CreateModel(
            name="CompiledQuant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seekingalpha_symbol", models.CharField(max_length=10)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("top_rated_overall", "Overall"),
                            ("top_quant", "Quant"),
                            ("top_dividend", "Dividend"),
                            ("top_growth", "Growth"),
                            ("top_value", "Value"),
                            ("top_healthcare", "Healthcare"),
                            ("top_utility", "Utility"),
                            ("top_consumer_staples", "Consumer Staples"),
                            ("top_technology", "Technology"),
                            ("top_energy", "Energy"),
                            ("top_materials", "Materials"),
                            ("top_industrial", "Industrial"),
                            ("top_communication", "Communication"),
                            ("top_financial", "Financial"),
                        ],
                        max_length=255,
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("count", models.PositiveSmallIntegerField(default=0)),
                (
                    "compilation_date",
                    models.DateField(
                        auto_now=True, verbose_name="Date this row was compiled"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("seekingalpha_symbol", "type"), name="pk_compiledquant"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Quant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Year and month this data is from",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("top_rated_overall", "Overall"),
                            ("top_quant", "Quant"),
                            ("top_dividend", "Dividend"),
                            ("top_growth", "Growth"),
                            ("top_value", "Value"),
                            ("top_healthcare", "Healthcare"),
                            ("top_utility", "Utility"),
                            ("top_consumer_staples", "Consumer Staples"),
                            ("top_technology", "Technology"),
                            ("top_energy", "Energy"),
                            ("top_materials", "Materials"),
                            ("top_industrial", "Industrial"),
                            ("top_communication", "Communication"),
                            ("top_financial", "Financial"),
                        ],
                        max_length=255,
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField()),
                ("seekingalpha_symbol", models.CharField(max_length=10)),
                ("quant", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "rating_seeking_alpha",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "rating_wall_street",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("market_cap_millions", models.FloatField(blank=True, null=True)),
                (
                    "dividend_yield",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("valuation", models.CharField(max_length=2)),
                ("growth", models.CharField(max_length=2)),
                ("profitability", models.CharField(max_length=2)),
                ("momentum", models.CharField(max_length=2)),
                ("eps_revision", models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "type", "seekingalpha_symbol"),
                        name="unique_quant_date_type_symbol",
                    )
                ],
            },
        ),
    ]
