# Generated by Django 4.2.2 on 2023-07-01 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("watcher", "0004_stock_date_last_fetch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert",
                to="watcher.stock",
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price",
                to="watcher.stock",
            ),
        ),
    ]
