# Generated by Django 4.2.2 on 2023-07-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watcher", "0005_alter_alert_stock_alter_price_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="days",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="alert",
            name="value",
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
