# Generated by Django 5.1.4 on 2025-01-15 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watcher", "0006_quantstock_remove_compiledquant_pk_compiledquant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quant",
            name="rating_seeking_alpha",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=3,
                null=True,
                verbose_name="Seeking Alpha Rating",
            ),
        ),
        migrations.AlterField(
            model_name="quant",
            name="rating_wall_street",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=3,
                null=True,
                verbose_name="Wall Street Rating",
            ),
        ),
        migrations.AlterField(
            model_name="quantstock",
            name="stock",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quant_stock",
                to="watcher.stock",
            ),
        ),
    ]
