# Generated by Django 5.1.4 on 2025-01-22 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watcher", "0008_compiledquantdecay_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="watcher.stock",
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="watcher.stock",
            ),
        ),
    ]
