# Generated by Django 5.1.4 on 2025-05-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watcher", "0009_alter_alert_stock_alter_price_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Cheapest In X Days"),
                    (2, "Most Expensive In X Days"),
                    (3, "Lower Than"),
                    (4, "Higher Than"),
                    (5, "Price changed by at least X%"),
                ]
            ),
        ),
    ]
