# Generated by Django 5.1.4 on 2025-05-12 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watcher", "0010_alter_alert_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="compiledquant",
            name="compiled_quant__unique__quant_stock__type",
        ),
        migrations.RemoveConstraint(
            model_name="compiledquantdecay",
            name="compiled_quant_decay__unique__quant_stock__type",
        ),
        migrations.RemoveConstraint(
            model_name="quant",
            name="quant__unique__date__type__quant_stock",
        ),
        migrations.RemoveField(
            model_name="compiledquant",
            name="quant_stock",
        ),
        migrations.RemoveField(
            model_name="compiledquantdecay",
            name="quant_stock",
        ),
        migrations.RemoveField(
            model_name="quant",
            name="quant_stock",
        ),
        migrations.RemoveField(
            model_name="quantstock",
            name="stock",
        ),
    ]
