# Generated by Django 5.1.4 on 2025-05-12 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "watcher",
            "0011_remove_compiledquant_compiled_quant__unique__quant_stock__type_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompiledQuant",
        ),
        migrations.DeleteModel(
            name="CompiledQuantDecay",
        ),
        migrations.DeleteModel(
            name="Quant",
        ),
        migrations.DeleteModel(
            name="QuantStock",
        ),
    ]
