# Generated by Django 5.1.4 on 2025-05-17 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("watcher", "0012_delete_compiledquant_delete_compiledquantdecay_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SAStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "stock",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sa_stock",
                        to="watcher.stock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SARating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Year and month this data is from",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("top_rated_overall", "Overall"),
                            ("top_quant", "Quant"),
                            ("top_dividend", "Dividend"),
                            ("top_growth", "Growth"),
                            ("top_value", "Value"),
                            ("top_healthcare", "Healthcare"),
                            ("top_utility", "Utility"),
                            ("top_consumer_staples", "Consumer Staples"),
                            ("top_technology", "Technology"),
                            ("top_energy", "Energy"),
                            ("top_materials", "Materials"),
                            ("top_industrial", "Industrial"),
                            ("top_communication", "Communication"),
                            ("top_financial", "Financial"),
                        ],
                        max_length=255,
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField()),
                ("quant", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "rating_seeking_alpha",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="Seeking Alpha Rating",
                    ),
                ),
                (
                    "rating_wall_street",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="Wall Street Rating",
                    ),
                ),
                ("market_cap_millions", models.FloatField(blank=True, null=True)),
                (
                    "dividend_yield",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("valuation", models.CharField(max_length=2)),
                ("growth", models.CharField(max_length=2)),
                ("profitability", models.CharField(max_length=2)),
                ("momentum", models.CharField(max_length=2)),
                ("eps_revision", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "sa_stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quant.sastock"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "type", "sa_stock"),
                        name="quant__sa_rating__unique__date__type__sa_stock",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CompiledSAScoreDecayed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("top_rated_overall", "Overall"),
                            ("top_quant", "Quant"),
                            ("top_dividend", "Dividend"),
                            ("top_growth", "Growth"),
                            ("top_value", "Value"),
                            ("top_healthcare", "Healthcare"),
                            ("top_utility", "Utility"),
                            ("top_consumer_staples", "Consumer Staples"),
                            ("top_technology", "Technology"),
                            ("top_energy", "Energy"),
                            ("top_materials", "Materials"),
                            ("top_industrial", "Industrial"),
                            ("top_communication", "Communication"),
                            ("top_financial", "Financial"),
                        ],
                        max_length=255,
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("count", models.PositiveSmallIntegerField(default=0)),
                (
                    "latest_sa_ratings_date",
                    models.DateField(
                        verbose_name="Date of the latest Seeking Alpha ratings dump used for compilation"
                    ),
                ),
                (
                    "sa_stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quant.sastock"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Compiled sa scores decayed",
                "db_table": "quant_compiledsascorebase_decay",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sa_stock", "type"),
                        name="quant__compiled_score_decayed__unique__sa_stock__type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CompiledSAScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("top_rated_overall", "Overall"),
                            ("top_quant", "Quant"),
                            ("top_dividend", "Dividend"),
                            ("top_growth", "Growth"),
                            ("top_value", "Value"),
                            ("top_healthcare", "Healthcare"),
                            ("top_utility", "Utility"),
                            ("top_consumer_staples", "Consumer Staples"),
                            ("top_technology", "Technology"),
                            ("top_energy", "Energy"),
                            ("top_materials", "Materials"),
                            ("top_industrial", "Industrial"),
                            ("top_communication", "Communication"),
                            ("top_financial", "Financial"),
                        ],
                        max_length=255,
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("count", models.PositiveSmallIntegerField(default=0)),
                (
                    "latest_sa_ratings_date",
                    models.DateField(
                        verbose_name="Date of the latest Seeking Alpha ratings dump used for compilation"
                    ),
                ),
                (
                    "sa_stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quant.sastock"
                    ),
                ),
            ],
            options={
                "db_table": "quant_compiledsascorebase_regular",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sa_stock", "type"),
                        name="quant__compiled_score__unique__sa_stock__type",
                    )
                ],
            },
        ),
    ]
