# Generated by Django 5.2 on 2025-07-02 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quant", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="compiledsascoredecayed",
            table="quant_compiledsascorebase_decayed",
        ),
        migrations.CreateModel(
            name="CompiledSADeltaScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("top_rated_overall", "Overall"),
                            ("top_quant", "Quant"),
                            ("top_dividend", "Dividend"),
                            ("top_growth", "Growth"),
                            ("top_value", "Value"),
                            ("top_healthcare", "Healthcare"),
                            ("top_utility", "Utility"),
                            ("top_consumer_staples", "Consumer Staples"),
                            ("top_technology", "Technology"),
                            ("top_energy", "Energy"),
                            ("top_materials", "Materials"),
                            ("top_industrial", "Industrial"),
                            ("top_communication", "Communication"),
                            ("top_financial", "Financial"),
                        ],
                        max_length=255,
                    ),
                ),
                ("count", models.PositiveSmallIntegerField(default=0)),
                (
                    "latest_sa_ratings_date",
                    models.DateField(
                        verbose_name="Date of the latest Seeking Alpha ratings dump used for compilation"
                    ),
                ),
                ("combined_score", models.DecimalField(decimal_places=2, max_digits=4)),
                ("slope_score", models.DecimalField(decimal_places=2, max_digits=4)),
                ("rank_score", models.DecimalField(decimal_places=2, max_digits=4)),
                ("ranks", models.JSONField(default=list)),
                (
                    "sa_stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quant.sastock"
                    ),
                ),
            ],
            options={
                "db_table": "quant_compiledsascorebase_delta_regular",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sa_stock", "type"),
                        name="quant__compiled_delta__unique__sa_stock__type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CompiledSADeltaScoreDecayed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("top_rated_overall", "Overall"),
                            ("top_quant", "Quant"),
                            ("top_dividend", "Dividend"),
                            ("top_growth", "Growth"),
                            ("top_value", "Value"),
                            ("top_healthcare", "Healthcare"),
                            ("top_utility", "Utility"),
                            ("top_consumer_staples", "Consumer Staples"),
                            ("top_technology", "Technology"),
                            ("top_energy", "Energy"),
                            ("top_materials", "Materials"),
                            ("top_industrial", "Industrial"),
                            ("top_communication", "Communication"),
                            ("top_financial", "Financial"),
                        ],
                        max_length=255,
                    ),
                ),
                ("count", models.PositiveSmallIntegerField(default=0)),
                (
                    "latest_sa_ratings_date",
                    models.DateField(
                        verbose_name="Date of the latest Seeking Alpha ratings dump used for compilation"
                    ),
                ),
                ("combined_score", models.DecimalField(decimal_places=2, max_digits=4)),
                ("slope_score", models.DecimalField(decimal_places=2, max_digits=4)),
                ("rank_score", models.DecimalField(decimal_places=2, max_digits=4)),
                ("ranks", models.JSONField(default=list)),
                (
                    "sa_stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quant.sastock"
                    ),
                ),
            ],
            options={
                "db_table": "quant_compiledsascorebase_delta_decayed",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sa_stock", "type"),
                        name="quant__compiled_delta_decayed__unique__sa_stock__type",
                    )
                ],
            },
        ),
    ]
