# Generated by Django 6.0.5 on 2026-06-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0002_compiledsascoremomentum_and_signed_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='sastock',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sastock',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='sastock',
            name='review_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
