# Generated by Django 6.0.5 on 2026-06-04 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0003_sastock_external_id_sastock_needs_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sastock',
            name='needs_review',
        ),
        migrations.RemoveField(
            model_name='sastock',
            name='review_note',
        ),
    ]
