# Generated by Django 4.2.2 on 2023-07-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watcher", "0003_alter_stock_currency_alter_stock_market"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="alphavantage_symbol",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="iex_symbol",
        ),
        migrations.AddField(
            model_name="stock",
            name="marketstack_symbol",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Marketstack API symbol (if different)",
            ),
        ),
    ]
