# Generated by Django 5.1.4 on 2025-01-13 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "watcher",
            "0005_stock_dividend_yield_alter_alert_days_compiledquant_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="QuantStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="compiledquant",
            name="pk_compiledquant",
        ),
        migrations.RemoveConstraint(
            model_name="quant",
            name="unique_quant_date_type_symbol",
        ),
        migrations.RemoveField(
            model_name="compiledquant",
            name="compilation_date",
        ),
        migrations.RemoveField(
            model_name="compiledquant",
            name="seekingalpha_symbol",
        ),
        migrations.RemoveField(
            model_name="quant",
            name="seekingalpha_symbol",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="google_symbol",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="marketstack_symbol",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="seekingalpha_symbol",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="yahoo_symbol",
        ),
        migrations.AddField(
            model_name="alert",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="compiledquant",
            name="latest_quant_date",
            field=models.DateField(
                verbose_name="Date of the latest quant dump used for compilation",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stock",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="quantstock",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="watcher.stock",
            ),
        ),
        migrations.AddField(
            model_name="compiledquant",
            name="quant_stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="watcher.quantstock",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quant",
            name="quant_stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="watcher.quantstock",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="compiledquant",
            constraint=models.UniqueConstraint(
                fields=("quant_stock", "type"), name="pk_stock_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="quant",
            constraint=models.UniqueConstraint(
                fields=("date", "type", "quant_stock"), name="pk_date_type_stock"
            ),
        ),
    ]
