# Generated by Django 5.1.4 on 2025-01-17 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watcher", "0007_alter_quant_rating_seeking_alpha_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompiledQuantDecay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("top_rated_overall", "Overall"),
                            ("top_quant", "Quant"),
                            ("top_dividend", "Dividend"),
                            ("top_growth", "Growth"),
                            ("top_value", "Value"),
                            ("top_healthcare", "Healthcare"),
                            ("top_utility", "Utility"),
                            ("top_consumer_staples", "Consumer Staples"),
                            ("top_technology", "Technology"),
                            ("top_energy", "Energy"),
                            ("top_materials", "Materials"),
                            ("top_industrial", "Industrial"),
                            ("top_communication", "Communication"),
                            ("top_financial", "Financial"),
                        ],
                        max_length=255,
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("count", models.PositiveSmallIntegerField(default=0)),
                (
                    "latest_quant_date",
                    models.DateField(
                        verbose_name="Date of the latest quant dump used for compilation"
                    ),
                ),
            ],
            options={
                "db_table": "compiledquantbase_decay",
            },
        ),
        migrations.RemoveConstraint(
            model_name="compiledquant",
            name="pk_stock_type",
        ),
        migrations.RemoveConstraint(
            model_name="price",
            name="unique_stock_date",
        ),
        migrations.RemoveConstraint(
            model_name="quant",
            name="pk_date_type_stock",
        ),
        migrations.AddConstraint(
            model_name="compiledquant",
            constraint=models.UniqueConstraint(
                fields=("quant_stock", "type"),
                name="compiled_quant__unique__quant_stock__type",
            ),
        ),
        migrations.AddConstraint(
            model_name="price",
            constraint=models.UniqueConstraint(
                fields=("stock", "date"), name="price__unique__stock__date"
            ),
        ),
        migrations.AddConstraint(
            model_name="quant",
            constraint=models.UniqueConstraint(
                fields=("date", "type", "quant_stock"),
                name="quant__unique__date__type__quant_stock",
            ),
        ),
        migrations.AlterModelTable(
            name="compiledquant",
            table="compiledquantbase_regular",
        ),
        migrations.AddField(
            model_name="compiledquantdecay",
            name="quant_stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="watcher.quantstock"
            ),
        ),
        migrations.AddConstraint(
            model_name="compiledquantdecay",
            constraint=models.UniqueConstraint(
                fields=("quant_stock", "type"),
                name="compiled_quant_decay__unique__quant_stock__type",
            ),
        ),
    ]
